name: CI

on: [push, pull_request]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint Addon
        run: yarn lint
        working-directory: ember-toggle
      - name: Lint Test App
        run: yarn lint
        working-directory: test-app

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    working-directory: test-app
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test:ember --launch ${{ matrix.browser }}

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --no-lockfile --non-interactive
      - name: Test
        run: yarn test:ember --launch ${{ matrix.browser }}

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-default-with-jquery
          - ember-classic
        allow-failure: [false]
        include:
          - ember-try-scenario: ember-canary
            allow-failure: true
          - ember-try-scenario: embroider-safe
            allow-failure: true
          - ember-try-scenario: embroider-optimized
            allow-failure: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
